# Giá trị token cho các loại block
block-values:
  COBBLESTONE: 1
  RAW_IRON: 2
  RAW_GOLD: 5
  DIAMOND: 10
  STONE: 3
  IRON_ORE: 4
  GOLD_ORE: 10
  DIAMOND_ORE: 20
# Thêm phần này vào file config.yml của NFTMiner
minepath:
  host: localhost
  port: 3306
  database: minepath
  username: solana
  password: solana
  
# Tỷ lệ sinh ra các loại quặng trong khu đào (tổng nên bằng 1.0)
ore-rates:
  stone: 0.7
  iron_ore: 0.15
  gold_ore: 0.1
  diamond_ore: 0.05

# Khu vực MiningBox (tọa độ tính trong thế giới mỏ riêng)
mine-box:
  min-x: 10
  min-y: 10
  min-z: 10
  width: 15  # Kích thước theo trục X: 15 blocks
  height: 8  # Kích thước theo trục Y: 8 blocks
  length: 15 # Kích thước theo trục Z: 15 blocks

# Cấu hình nâng cấp tốc độ
speed-upgrade:
  # Cấp độ tối đa
  max-level: 5

  # Giá nâng cấp mỗi cấp (token)
  costs:
    1: 500
    2: 700
    3: 900
    4: 1000
    5: 1200

  # Cấp độ hiệu ứng Haste mỗi cấp
  effects:
    1: 0  # Cấp 1: Không có hiệu ứng
    2: 1  # Cấp 2: Haste I
    3: 2  # Cấp 3: Haste II
    4: 3  # Cấp 4: Haste III
    5: 4  # Cấp 5: Haste IV

inventory-upgrade:
  max-level: 3
  costs:
    1: 200
    2: 500
    3: 1000

# Cấu hình nâng cấp giá trị token
token-value-upgrade:
  max-level: 5
  costs:
    1: 100
    2: 250
    3: 500
    4: 1000
    5: 2000
  multipliers:
    1: 1.2
    2: 1.5
    3: 2.0
    4: 2.5
    5: 3.0

# Cấu hình tỉ lệ rớt NFT
nft-drop:
  # Cơ hội cơ bản để rơi NFT (0.05 = 5%)
  # Đặt thấp để tạo cảm giác hiếm và quý giá
  base-drop-chance: 0.05

  # Thời gian chờ giữa các lần rơi NFT (giây)
  # Đặt 300 giây (5 phút) để tránh farm quá nhanh
  cooldown-seconds: 300

  # Tỉ lệ rơi theo độ hiếm (%)
  # Tăng tỉ lệ common và uncommon, giảm tỉ lệ legendary
  rarity-drop-rates:
    common: 60.0
    uncommon: 25.0
    rare: 10.0
    epic: 4.0
    legendary: 1.0

  # Cài đặt buff
  buffs:
    # Bật/tắt hệ thống buff
    enabled: true

    # Giới hạn buff luck tối đa (0.15 = 15%)
    # Giảm xuống để không quá mạnh
    max-luck-buff: 0.15

  # Cấu hình tỉ lệ rơi NFT theo độ hiếm
  tiers:
    common:
      lucky_charm_1: 60
      explosion_pickaxe_1: 15  # Giảm từ 30 xuống 15
      laser_pickaxe_1: 25      # Tăng từ 20 lên 25

    uncommon:
      lucky_charm_2: 60
      explosion_pickaxe_2: 15  # Giảm từ 30 xuống 15
      laser_pickaxe_2: 25      # Tăng từ 20 lên 25

    rare:
      lucky_charm_5: 60
      explosion_pickaxe_3: 15  # Giảm từ 30 xuống 15
      laser_pickaxe_3: 25      # Tăng từ 20 lên 25

    epic:
      lucky_charm_10: 60
      explosion_pickaxe_4: 15  # Giảm từ 30 xuống 15
      laser_pickaxe_4: 25      # Tăng từ 20 lên 25

    legendary:
      lucky_charm_20: 60
      explosion_pickaxe_5: 10  # Giảm từ 15 xuống 10
      laser_pickaxe_5: 30      # Tăng từ 15 lên 30