name: Miner-Simulator
version: '1.0.0'
main: me.tien.miner_simulator.Miner_Simulator
api-version: 1.18
softdepend: [NFTPlugin]
description: Plugin đào NFT với hệ thống buff từ NFT-Plugin
commands:
  claim:
    description: Nhận mine của bạn
    usage: /claim
    permission: miner_simulator.miningbox
  resetmine:
    description: Đặt lại mine của bạn
    usage: /resetmine
    permission: miner_simulator.miningbox
  miningbox:
    description: Teleport đến khu đào cá nhân
    usage: /miningbox
    permission: miner_simulator.miningbox
  token:
    description: Xem thông tin về token
    usage: /token
    permission: miner_simulator.miningbox
  shop:
    description: Mở shop để nâng cấp
    usage: /shop
    permission: miner_simulator.miningbox
  resetupgrades:
    description: Đặt lại toàn bộ cấp độ nâng cấp
    usage: /resetupgrades
    permission: miner_simulator.resetupgrades
  help:
    description: Xem thông tin về plugin
    usage: /help
    permission: miner_simulator.help

permissions:
  miner_simulator.miningbox:
    description: Cho phép sử dụng các lệnh cơ bản của NFTMiner
    default: true
  miner_simulator.resetupgrades:
    description: Cho phép đặt lại tất cả nâng cấp
    default: op
  miner_simulator.help:
    description: Cho phép xem thông tin trợ giúp về plugin
    default: true
